class Node:
    """Node class for representing nodes in the parse tree
    """
    def __init__(self, name, value=None):
        """Initialises a Node

        Args:
            name (str): non-terminal as described in the refactored BNF
            value (*, optional): Lexeme that is part of the program. Defaults to None.
        """
        self.name = name
        self.value = value
        self.children = []

    def add_child(self, child):
        """Appends a Node to the sub-tree generated by expanding a non-terminal

        Args:
            child (Node): token obtained after expanding a non-terminal
        """
        self.children.append(child)